In [1]:
1+1

2

In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
##sentences

sent=[
    'the glass of milk',
    'the cup of tea'
    ,'i am a good boy'
    ,'i am a good developer',
    'undersatnd the meaing of words ',
    'your videos are goods'
]

In [4]:
# define the vocabulary size
voc_size=10000

In [ ]:
### one hot representation
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr ## gives index of words where 1 in sparse matrix

[[4364, 5539, 3, 4028],
 [4364, 2170, 3, 3021],
 [5239, 4223, 6718, 8645, 7860],
 [5239, 4223, 6718, 8645, 6619],
 [2170, 4364, 4550, 3, 2074],
 [6354, 3013, 8195, 568]]

In [6]:
## word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [ ]:
 ## need to define the timesatmp but 
 # the sentences have diff no. of words so we choose max length
sent_length=8
# its add other words vector to 0(fixed size of all sentences)
embedded_docs=pad_sequences(one_hot_repr
                            ,padding='pre',
                            maxlen=sent_length)  

print(embedded_docs) 

[[   0    0    0    0 4364 5539    3 4028]
 [   0    0    0    0 4364 2170    3 3021]
 [   0    0    0 5239 4223 6718 8645 7860]
 [   0    0    0 5239 4223 6718 8645 6619]
 [   0    0    0 2170 4364 4550    3 2074]
 [   0    0    0    0 6354 3013 8195  568]]


In [8]:
## feature representation
dim=10

In [11]:
# model create
model=Sequential()
model.add(Embedding(input_dim=voc_size,output_dim=dim))
model.compile(
    optimizer='adam',
    loss='mse'
)

In [12]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 246ms/step


array([[[-0.02213219,  0.01875509,  0.00757507,  0.03107897,
         -0.00241414,  0.0395803 , -0.01450833,  0.00733429,
          0.01156297, -0.0189754 ],
        [-0.02213219,  0.01875509,  0.00757507,  0.03107897,
         -0.00241414,  0.0395803 , -0.01450833,  0.00733429,
          0.01156297, -0.0189754 ],
        [-0.02213219,  0.01875509,  0.00757507,  0.03107897,
         -0.00241414,  0.0395803 , -0.01450833,  0.00733429,
          0.01156297, -0.0189754 ],
        [-0.02213219,  0.01875509,  0.00757507,  0.03107897,
         -0.00241414,  0.0395803 , -0.01450833,  0.00733429,
          0.01156297, -0.0189754 ],
        [-0.03874687,  0.01529616, -0.015155  , -0.01244447,
         -0.03957865,  0.03489757,  0.02515185, -0.01274096,
         -0.04275183,  0.01014427],
        [-0.02237939,  0.04992925, -0.01842849, -0.00593482,
         -0.02556571,  0.01308514, -0.03770787,  0.04647063,
          0.00384591, -0.0412699 ],
        [ 0.01790262,  0.02073513,  0.03317609,  0.0